EDUARDO_KESLER = 541345392038641674
EDUARDO_MACHADO = 539545498386956319

charadas = [
    {
        'pergunta': 'Qual é o animal que anda com as patas?',
        'resposta': 'Todos os animais andam com as patas!'
    },
    {
        'pergunta': 'O que é o que é: quanto mais seca, mais molhada fica?',
        'resposta': 'A toalha!'
    },
    # Adicione mais charadas aqui
]

enigmas = [
    {
        "pergunta": "O que é que quanto mais se tira, maior fica?",
        "resposta": "O buraco."
    },
    {
        "pergunta": "O que é que quanto mais se lava, mais sujo fica?",
        "resposta": "A água."
    },
    {
        "pergunta": "O que é que tem chaves mas não abre portas?",
        "resposta": "Um teclado."
    },
    # Adicione mais enigmas aqui
]

elogios = [
        "Você é incrível!",
        "Suas habilidades são impressionantes!",
        "Você tem um coração gentil e generoso!",
        "Sua criatividade é inspiradora!",
        "Você sempre traz uma energia positiva para o grupo!",
        "Sua dedicação é admirável!",
        "Seu sorriso ilumina o dia de todos!",
        "Você é uma pessoa muito especial!",
        "Você é uma fonte de inspiração para os outros!",
        "Sua amizade é um presente para todos nós!"
    ]

jokes = [
    "Por que o pintinho não corre? Porque ele é a última bolinha do saco!",
    "Você sabia que o elefante pula de paraquedas? Pula, pula, pula, pula dedo!",
    "Por que a aranha é o animal mais carente do mundo? Porque ela é um aracneedyou!",
    "Você sabia que um monte de pregos morreu? Foi uma morte ferrada!",
    "Qual é o animal mais antigo? A zebra, porque está sempre nas listas de animais em extinção!",
    "Por que a vaca foi para o espaço? Para encontrar o vácuo!",
    "Qual é o contrário de volátil? Vem cá, sobrinho!",
    "O que o tomate foi fazer no banco? Foi tirar extrato (ex-trato)!",
    "Qual o mês que você não pode confiar? Março, porque é uma marcha lenta!",
    "Por que o livro de matemática se apaixonou? Porque tinha problemas a resolver!",
    "O que um cromossomo disse para o outro? Cromossomos bonitos não pares!",
    "Qual o legume que é um super-herói? O Super Chuchu!",
    "Por que a estrela não empresta dinheiro? Porque ela sempre está no céu!",
    "Por que o pato foi preso? Porque ele era o único que estava 'quentinho'!",
    "O que a impressora disse para o papel? Esse é um rolo que só acaba em tinta!",
    "Qual o cúmulo do desligamento? Chutar o balde e acertar o pé!",
    "Por que o cinema estava com o ar condicionado ligado? Porque estava perto do ventilador!",
    "O que é um pontinho vermelho no canto da sala? Uma cereja de castigo!",
    "Qual é o país que sempre está em primeiro lugar? O Iraque, porque vem antes de todos!",
    "Qual é o doce preferido dos átomos? Pé-de-moléculas!",
    "Por que o jacaré tirou o jacarezinho da escola? Porque ele réptil de ano!",
    "Por que a planta estava na prisão? Porque cometeu fotossíntese!",
    "Você sabe o que o canibal vegetariano come? A planta do pé!",
    "O que um amigo falou para o outro na hora de ir embora? 'Foi um lanche!'",
    "Qual o contrário de 'noite de luz'? 'Dia de trevas'!",
    "O que o biscoito disse para o outro? Vamos dar um 'rolê' juntos!",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual o time que é uma piada? O Palmeiras, porque tem cinco 'piadas' (títulos)!",
    "Por que a minhoca não brinca esconde-esconde? Porque ela se entrega!",
    "O que o pássaro falou para o outro na hora de viajar? 'Vamos de 'beak' (bic)icleta!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual é o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o carro que o Thor usa? O Fer-rari!",
    "Por que o pato foi para a escola? Porque queria melhorar o seu 'quaque'!",
    "O que o pneu falou para o carro? 'A nossa relação está rolando bem!'",
    "Qual a bebida favorita dos pássaros? O suco de 'laran-ja'!",
    "Por que o livro estava sorrindo? Porque ele tinha muitas 'piadas literárias'!",
    "O que o advogado da cebola falou? 'Tudo isso é 'choro'!'",
    "Qual é o personagem que sempre manda 'em-bora'? O Em-bu!",
    "Por que a formiga só tira notas boas na escola? Porque ela é 'aplicada'!",
    "O que o cesto de roupa suja disse para o ferro de passar? 'Você me deixa 'lisinho'!",
    "Qual é o carro que chora? O Sussu-susuki!",
    "Por que a minhoca foi ao médico? Porque estava se sentindo um pouco 'escorregadia'!",
    "O que a fada madrinha disse para o feijão? 'Vai feijão, seja feliz!'",
    "Qual é o país que cai aos pedaços? A Tchecoslováquia!",
    "Por que a vassoura estava nervosa? Porque estava 'varrendo' da vida!",
    "O que a cenoura disse para o tomatinho? 'Você é um 'tomate' de estimação'!",
    "Qual é o bicho que caiu do décimo andar e não quebrou? O passarinho, porque ele voa!",
    "Por que a melancia não pode ser goleira? Porque ela não aguenta um 'gol'!",
    "O que o lápis disse para a borracha? 'Você apaga o meu passado!'",
    "Qual o animal que vive em cima do piano? O 'pianco'!",
    "Por que o gato não gosta de apostas? Porque ele tem medo de 'arriscar'!",
    "O que o tijolo falou para o outro? 'Há um ci-me-n-to (ciumento) entre nós!'",
    "Qual é o contrário de 'licença poética'? 'Carroça enlatada'!",
    "Por que o livro de matemática estava sempre com frio? Porque ele tinha 'problemas térmicos'!",
    "O que o pneu disse para o carro? 'Não fuja de mim!'",
    "Qual é o doce preferido do átomo? Pé-de-moléculas!",
    "Por que a aranha é uma ótima escritora? Porque ela é 'charantrã'!",
    "O que a vaca foi fazer no espaço? Foi encontrar o vácuo!",
    "Qual é o país que só tem trem? O Trenegal!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "O que o lápis falou para a borracha? 'Nossa, como você é 'borracha'!",
    "Qual é o carro que o Hulk usa? O In-finiti!",
    "Por que a estrela nunca luta boxe? Porque ela brilha mas não é 'luz'tre!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual é o time que é uma piada? O Palmeiras, porque tem cinco 'piadas' (títulos)!",
    "Por que a minhoca não brinca de esconde-esconde? Porque ela se entrega!",
    "O que a impressora falou para o papel? Esse é um rolo que só acaba em tinta!",
    "Qual o legume que é um super-herói? O Super Chuchu!",
    "Por que o jacaré tirou o jacarezinho da escola? Porque ele réptil de ano!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "Qual o cúmulo do desligamento? Chutar o balde e acertar o pé!",
    "Por que o cinema estava com o ar condicionado ligado? Porque estava perto do ventilador!",
    "O que é um pontinho vermelho no canto da sala? Uma cereja de castigo!",
    "Qual é o país que sempre está em primeiro lugar? O Iraque, porque vem antes de todos!",
    "Qual é o doce preferido dos átomos? Pé-de-moléculas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a formiga é o animal mais carente do mundo? Porque ela é um aracneedyou!",
    "Você sabia que um monte de pregos morreu? Foi uma morte ferrada!",
    "O que a planta estava fazendo na prisão? Fotossíntese!",
    "Você sabe o que o canibal vegetariano come? A planta do pé!",
    "Por que o livro de matemática se apaixonou? Porque tinha problemas a resolver!",
    "O que um cromossomo disse para o outro? Cromossomos bonitos não pares!",
    "Qual é o animal mais antigo? A zebra, porque está sempre nas listas de animais em extinção!",
    "Por que a vaca foi para o espaço? Para encontrar o vácuo!",
    "Qual é o contrário de volátil? Vem cá, sobrinho!",
    "O que o tomate foi fazer no banco? Foi tirar extrato (ex-trato)!",
    "Qual o mês que você não pode confiar? Março, porque é uma marcha lenta!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pássaro falou para o outro na hora de viajar? 'Vamos de 'beak' (bic)icleta!'",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual o time que é uma piada? O Palmeiras, porque tem cinco 'piadas' (títulos)!",
    "Por que a minhoca não brinca esconde-esconde? Porque ela se entrega!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
    "Por que o livro de matemática se odiava? Porque ele tinha muitos problemas!",
    "O que o pagodeiro foi fazer na igreja? Foi cantar 'Salmo - Pago'!",
    "Por que a Coca-Cola não pode se casar? Porque ela perdeu o 'Fanta'sma'!",
    "Qual o doce preferido do geólogo? O rochambole!",
    "O que o sushi disse para o sashimi? 'Te ligo no 'sashimorro' (sábado)'!'",
    "Por que a Coca-Cola foi ao médico? Porque ela estava 'Fanta-siada'!",
    "Qual o estado que ninguém gosta? O estado 'líquido', porque sempre escorre pelas mãos!",
    "O que a impressora disse para a outra? Essa folha é sua ou é uma 'im-pasta' (imposto)?",
    "Por que o marido da mulher de meia idade foi ao desfile? Porque ela é sua 'meia' melhor!",
    "Qual a comida que luta boxe? O quibe!",
    "O que a água falou para o açúcar? 'Me ajuda que estou 'açucarada'!",
    "Por que a menina não entrou no restaurante? Porque ela era menor de 'idade'!",
    "Qual é o super-herói que adora feijoada? É o 'Feijoão'!",
    "O que a azeitona foi fazer no teatro? Foi ver a 'peça'!",
    "Por que o louco não usa redes sociais? Porque ele já vive 'twittando' na vida real!",
    "O que o café foi fazer na igreja? Foi orar o 'pãopurério'!",
    "Qual é o doce mais engraçado? O sorriso-lém!",
    "Por que o morcego nunca fica doente? Porque ele se pendura na vitamina C!",
    "Você sabe por que a foca olhava sempre pro céu? Porque lá tinha 'Estrela'!",
    "O que o vinho falou para o queijo? 'Eu te amontoa!'",
    "Por que a melancia foi ao médico? Porque ela estava se sentindo 'meloncolia'!",
    "O que o chá foi fazer na delegacia? Foi prestar 'in-fusão'!",
    "Qual é o carro mais apressado? O Fusca, porque ele 'passa'tempo!",
    "Por que o livro de física estava com tanto calor? Porque tinha muitos problemas 'termais'!",
    "O que a terra falou para a lua? 'A gente se 'sol'ta, mas sempre se 'lua'!",
    "Qual o país mais engraçado? O 'Hahamericano'!",
    "Por que a água foi no psiquiatra? Porque ela se sentia 'instável'!",
    "O que o pato disse para a pata? 'Vem quá'!",
    "Qual o lugar que é impossível esconder um pote de ouro? No arco-íris!",
    "Por que a pipoca nunca comete crimes? Porque ela estoura de medo da polícia!",
    "O que o zero falou para o oito? 'Está com um cinto muito 'fashion' (fashion - oito)'!",
    "Qual é o animal que sempre está pronto para a guerra? O guerreiro!",
    "Por que o computador não usa chapéu? Porque ele já tem um 'Windows'!",
    "O que o tomate falou para o outro? 'Vamos 'catchup' (catch up - alcançar)!'",
    "Qual é o rei dos queijos? O reiqueijão!",
    "Por que a TV não vai à praia? Porque ela já tem uma tela!",
    "Qual é o contrário de 'sossego'? 'Dorme perto'!",
    "O que a formiga foi fazer na balada? Foi dançar 'funk ant'!",
    "Por que a formiga é atômica? Porque ela é pequena, mas não perde uma bomba!",
    "O que o macaco disse para o banana? 'Me descasque que estou passando!'",
    "Qual é o animal mais antigo? O zeb-RA",
    "O que o pato falou para a pata? Vem 'patinhá'!",
]
